### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by elfring** [chneukirchen/nq#10]
I suggest to reuse a higher level build system than [your current small make file](https://github.com/chneukirchen/nq/blob/106586cef8425276e4f2ac1eacc180adaad50968/Makefile#L1 "Update candidate") so that powerful checks for software features will become easier.
* [CMake](http://cmake.org/ "CMake build system")
* [Autotools](http://www.gnu.org/software/autoconf/#TOCintroduction "GNU build system")

**Comment by chneukirchen** [comment]
I added a `make install` rule, I think this is now totally sufficient for such a small tool.

**Comment by elfring** [comment]
* Does [a tool like "autoscan"](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/autoscan-Invocation.html "Using autoscan to create configure.ac") show any software dependencies that you find worth for further considerations?
* How do you think about to support more development environments by [the reuse of build system generators](http://www.cmake.org/cmake/help/v3.3/manual/cmake-generators.7.html#cmake-generators "Selection for build tool generators")?

**Comment by chneukirchen** [comment]
The `configure.scan` generated by autoscan only seems to list things that are in POSIX 2008, which is the documented requirement.

And we don't need cmake to compile two files, thanks. ;)
