### ISSUE TITLE
support illumos with fcntl

### ISSUE THREAD

**Issue by josephholsten** [chneukirchen/nq#17]
I wrote a portable `flock(1)` a while back and I wanted it to work similarly on bsd, linux & illumos. I ended up reviewing different `flock(2)` emulation impls out there and came up with https://github.com/discoteq/flock/blob/master/src/flock.c#L26

Interested in me adding illumos support?

**Comment by chneukirchen** [comment]
According to http://www.perkin.org.uk/posts/solaris-portability-flock.html this has two issues which nq critically depends on:

- fcntl() locks are not held across a fork(), so you cannot pass locks down to child processes.

- The semantics of fcntl() are such that any closure of a file descriptor in your application will release the locks held against that file.

So, I don't think this will work out?

**Comment by chneukirchen** [comment]
The code now works on SmartOS thanks to https://github.com/joyent/illumos-joyent/commit/ade223c
and probably on Illumos https://github.com/illumos/illumos-gate/commit/7a5aac98bc37534537d4896efd4efd30627d221e

This function will be available on OmniOS with the import of LX branded zones, I guess.
