### ISSUE TITLE
list all the queued task even none-executed ones?

### ISSUE THREAD

**Issue by gotbletu** [chneukirchen/nq#19]
This command **$fq -qa** only shows task that has been executed already.
Is there a way to list all task that has **NOT** been executed yet also?
Sometimes i add a lot to the queue but forgot which things i added already.

**Comment by chneukirchen** [comment]
I guess it would be useful. Try 3815763 with `fq -qn`.

**Comment by gotbletu** [comment]
Thanks that works =) , would great if it had a status next to it also, like **(running, finished, queue)** next to the commands and also an Exit-code Status **(0 or 1)** to see which commands failed or not ; similar to task-spooler

**Comment by chneukirchen** [comment]
Exit status is only tracked as a message in the file.

FWIW, the running script has +x bit set, so probably ls -l already does what you want. :)

**Comment by gotbletu** [comment]
hehe alright thats fine, those wasnt that important to me
