### ISSUE TITLE
Flag to automatically delete lockfile?

### ISSUE THREAD

**Issue by Anachron** [chneukirchen/nq#24]
It would be cool if there is a flag that deletes the lockfile automatically after the command finished with RC=0.

**Comment by Anachron** [comment]
Nevermind, I'll write my own wrapper I guess.

**Comment by chneukirchen** [comment]
I think this is easy to add.

try https://0x0.st/sqsz.diff

**Comment by Anachron** [comment]
Thanks that was quick! 

Will you add it to the repo? Because I haven't set up my own builders for custom patches on void yet. 

If you say however that this tool is feature finished and new versions will barely come I would gladly compile it once more locally.

**Comment by chneukirchen** [comment]
No, I think it's a sensible feature. If this works as you want, I'll commit it.
