### ISSUE TITLE
nq sudo ... does not work

### ISSUE THREAD

**Issue by daveloyall** [chneukirchen/nq#7]
hobbes@hubris:~$ fq
    ==> ,14f6c6fbfb5.3605
    exec 'nq' 'sudo' 'apt-get' 'install' 'autoconf'
    
    sudo: no tty present and no askpass program specified
    
    [exited with status 1.]

**Comment by chneukirchen** [comment]
Well, yes, nq runs the applications noninteractively, so there is no way it can ask for a password.

You can use `sudo -v` to unlock sudo first, but note that this will still fail when the previous jobs took too long for the ticket to timeout.

Alternatively, you can run `sudo nq ...`, but then the `,*`-file is root-readable only.
