### ISSUE TITLE
Needs installation/setup instructions

### ISSUE THREAD

**Issue by coverband** [chneukirchen/nq#8]
The readme file is not clear on how to setup the utility and whether it's available via a package manager. If the user is asked to compile, then some basic directions and troubleshooting information would be helpful.

Thanks.

**Comment by akhyrul** [comment]
+1

**Comment by alaroldai** [comment]
I've done some work on a Homebrew formula for mac, but I'm not sure how to go about getting it reviewed/submitted. Any tips?

**Comment by chneukirchen** [comment]
I added and documented a `make install` rule for now.

There is no official release yet, and afaiu noone packaged it yet... I guess I'll prepare a 0.1 for the weekend.
