### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [chneukirchen/nq#9]
Would you like to add more error handling for return values from functions like the following?
- [dup2](http://pubs.opengroup.org/onlinepubs/9699919799/functions/dup2.html "Duplicate an open file descriptor.") ⇒ [main](https://github.com/chneukirchen/nq/blob/7063558a6e4698e59f83b5e9d31b40ab3aec713d/nq.c#L74)
- [flock](http://man7.org/linux/man-pages/man2/flock.2.html "Remove an existing lock.") ⇒ [islocked](https://github.com/chneukirchen/nq/blob/7ed07d34dc7f704222530e7e200f3f192cf85b59/fq.c#L35)

**Comment by chneukirchen** [comment]
Ok, let's see what could happen here...

`dup2`: EBADF for oldfd can't happen, EBADF for newfd could happen (with very low limits), same for EMFILE, EBUSY could happen on Linux I guess, EINTR could happen... probably we can just panic when anything bad happens here.

`flock`: I guess we should catch EINTR, and panic on ENOLCK... rest should not happen.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.

Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "AspectC++")?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](http://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?

**Comment by chneukirchen** [comment]
Ok, EINTR cannot happen either because we don't use signals.

I checked the dup2 calls now, I don't think islocked needs change.

I think your suggestions are overkill for a tiny 500 loc C progam. ;)

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2FC.2B.2B "Tools for static code analysis") also for your software?
